# Generated by Django 4.2.1 on 2023-05-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Second_Name', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
                ('Sur_Name', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(null=True, upload_to='photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price_1', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_pensioner', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_WWII', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
