# Generated by Django 4.2.1 on 2023-05-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luke_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='photo',
            new_name='photo_news',
        ),
    ]
