# Generated by Django 4.2.1 on 2023-05-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luke_app', '0003_service_dantist_service_massage_service_ultrasound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_dantist',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
