# Generated by Django 4.2.1 on 2023-05-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luke_app', '0004_alter_service_dantist_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктора'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='service_dantist',
            options={'verbose_name': 'Стоматологическая услуга', 'verbose_name_plural': 'Стоматологические услуги'},
        ),
        migrations.AlterModelOptions(
            name='service_massage',
            options={'verbose_name': 'Массаж', 'verbose_name_plural': 'Массаж'},
        ),
        migrations.AlterModelOptions(
            name='service_ultrasound',
            options={'verbose_name': 'УЗИ', 'verbose_name_plural': 'УЗИ'},
        ),
    ]
