# Generated by Django 4.2.1 on 2023-05-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luke_app', '0005_alter_doctor_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга Общая', 'verbose_name_plural': 'Услуги_Общие'},
        ),
        migrations.AlterModelOptions(
            name='service_massage',
            options={'verbose_name': 'Услуга Массаж', 'verbose_name_plural': 'Услуги Массажа'},
        ),
        migrations.AlterModelOptions(
            name='service_ultrasound',
            options={'verbose_name': 'Услуга УЗИ', 'verbose_name_plural': 'Услуги УЗИ'},
        ),
    ]
